spring:
  datasource:
    one:
      url: jdbc:mysql://127.0.0.1:3306/mohai_one?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
    two:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/mohai_two?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource